services:
  server:
    build:
      context: .
    # Add the command line options and web3:// websites to serve here
    # As an example, we serve web3://ocweb.eth
    # You can also serve multiple website this way (require a DNS domain per website): 
    # command: web3://0xAD41bf1c7f22F0ec988DaC4C0aE79119Cab9BB7E=terraformnavitagor.com web3://ocweb.eth=ocweb.com
    command: web3://ocweb.eth
    ports:
      - 80:80
      # - 443:443 # Uncomment if you enable HTTPS. Note: You must keep the 80 port open as well (used for SSL certificate generation)
    environment:
      NODE_ENV: production

      #
      # You can configure options via environment variables as well :
      #

      # Update the port here. Don't forget to update the port in the ports section as well
      PORT: 80

      # Force cache
      # FORCE_CACHE: true

      # Add/override chain RPCs
      # CHAIN_RPC: 1=https://eth-mainnet.alchemyapi.io/v2/XXX 123456789=http://127.0.0.1:8545

      # Update the root domain of the global web3:// gateway to use when a website is not served
      # by this gateway
      # GLOBAL_WEB3_HTTP_GATEWAY_DNS_DOMAIN: web3gateway.dev

      # Enable HTTPS with Let's Encrypt
      # Don't forget to update the ports section, and add DNS domains to your web3:// website in
      # the command section (e.g. web3://ocweb.eth=ocweb.com)
      # LETSENCRYPT_ENABLE_HTTPS: true
      # LETSENCRYPT_EMAIL: <your-email> # Required by Let's Encrypt
